[package]
name = "parser_rustreeem"
version = "0.1.0"
authors = ["khigasa <kojihigasa@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
lalrpop-util = "0.16.3"
regex = "0.2.1"

